export const LocationData = [
  "Denver, CO",
  "San Diego, CA",
  "Chicago, IL",
  "Miami, FL",
  "San Francisco, CA",
  "Los Angeles, CA",
  "Philadelphia, PA",
  "Seattle, WA",
  "Phoenix, AZ",
  "Houston, TX",
  "Dallas, TX",
  "Atlanta, GA",
  "Boston, MA",
  "New York City, NY",
];
